### ISSUE TITLE
GreenStalk University?

### ISSUE THREAD

**Issue by Vikctar** [devTimmy/E-Learning-Pad#1]
The privacy policy in [Register.cshtml](https://github.com/devTimmy/E-Learning-Pad/blob/master/web/Views/Account/Register.cshtml) line 43 is linked to a GreenStalk university. Is GreenStalk a pseudo term or an actual university? I think the privacy and terms should be attributed to e-learning pad.

**Comment by tmacharia** [comment]
GreenStalk is just a pseudo name, i don't think there is any university by that name.

So what happens is that E-Learning Pad is the platform/service and universities can use the platform. We will be building the platform using Greenstalk university as a use-case university or as a pilot university. You are also correct saying that privacy policy should be attributed to e-learning pad.

**Comment by Vikctar** [comment]
Ohh Okay. I get it now.
Safe to close this then

**Comment by Vikctar** [comment]
University name to be changed to Gobel Digital University.

**Comment by tmacharia** [comment]
Fixed!
